### ISSUE TITLE
setup.py not working on Ubuntu 14.10

### ISSUE THREAD

**Issue by CoChrists** [tjlane/thor#28]
Here are the changes I had to do in order to make it work:

```
139a140,144
>             cudaconfig_list=[{'home'   : home[x], 
>                               'nvcc'   : nvcc[x],
>                               'include': pjoin(home[x], 'include'),
>                               'lib64'  : pjoin(home[x], 'lib64')} \
>                              for x in xrange(len(home)) ]
148a154,158
>             cudaconfig_list=[{'home'   : home, 
>                               'nvcc'   : nvcc,
>                               'include': pjoin(home, 'include'),
>                               'lib64'  : pjoin(home, 'lib')} ]
>                               # 'lib64'  : pjoin(home, 'lib64')} ]
151,155d160
<         cudaconfig_list=[{'home'   : home[x], 
<                           'nvcc'   : nvcc[x],
<                           'include': pjoin(home[x], 'include'),
<                           'lib64'  : pjoin(home[x], 'lib64')} \
<                           for x in xrange(len(home)) ]
323c328,329
<         import pyfftw

---
>         # import pyfftw
>         import fftw3
```

**Comment by tjlane** [comment]
what's with the pyfftw vs fftw3 part?

want to open a pull request with these changes? that should check it against whatever version of ubuntu Travis is running. Then I can also test it on my mac easily.

TJ

**Comment by CoChrists** [comment]
I don't know. I guess it might be a naming convention thingy.

**Comment by CoChrists** [comment]
btw I don't expect these changes to work anywhere else. They are a hack to make it work, not a general solution...

**Comment by tjlane** [comment]
any chance I can convince you to develop & test a general soln :) ??

**Comment by dermen** [comment]
Why not add a " try/except ImportError " routine ?

-Derek

**Comment by tjlane** [comment]
There are 2 issues: the use of `lib` vs `lib64` paths, and `pyfftw` vs. `fftw3`.

@CoChrists can you confirm the origins of `fftw3`? It looks like `pyfftw3` and `pyfftw` are two completely different and unfortunately named packages.

The lib/lib64 issue is hopefully straightfoward, it would just help to have a little more info about the system setup that breaks it (in this case, Ubuntu 14). That's where @CoChrists can be a big help! Gundolf if you dont want to deal with it, give me an account on your machine :).

**Comment by CoChrists** [comment]
I am happy to help debugging this. I have installed all the python stuff from scratch on that machine. The fftw package I installed is named python-fftw (along with it's dependencies, of course).
What other info do you need?

**Comment by CoChrists** [comment]
This is still an issue on Ubuntu Xenial. Can I commit the changes?

**Comment by tjlane** [comment]
@CoChrists open a pull request if you can. I'll take a quick look and we can merge it into master.

**Comment by CoChrists** [comment]
I could, but actually we would need a general solution to the lib/lib64 and the pyfftw/fftw3 issues.

I am tempted to do just this for fftw issue:
```
[...]
    FFTW_NOSUCCESS = 0
    try:
        import pyfftw
        FFTW_NOSUCCESS = 0
    except:
        FFTW_NOSUCCESS = 1
    try:
        import fftw3
        FFTW_NOSUCCESS = 0
    except:
        FFTW_NOSUCCESS = 1

    if FFTW_NOSUCCESS:
        print()
        print('*'*65)
        print('* WARNING : PYFFTW SUPPORT')
        print('* --------------------------')
        print('* Could not load the pyfftw package, EVERYTHING WILL STILL')
[...]
```

**Comment by tjlane** [comment]
@CoChrists I'm a little confused. pyfftw and fftw3 are different python wrappers for fftw3. They don't have the same API, though, so they are not interchangeable. 

Further, the code above does not change anything in the execution of the actual simulation code -- so won't improve your performance. Just (incorrectly) get rid of a warning.

**Comment by CoChrists** [comment]
@tjlane This is indeed confusing. From the Ubuntu package description of python-fftw:
[http://packages.ubuntu.com/xenial/python-fftw](url)
> [...] PyFFTW are Python bindings for the FFTW3 C-routines, using numpy and ctypes. [...]

Now (in Xenial) we have a package called python-pyfftw again (was not present in Trusty). However it is currently broken until Ubuntu package maintainers decide to update:
[https://github.com/pyFFTW/pyFFTW/issues/112](url)
This means until the package is fixed one needs to either install pyfftw naually (e.g. via pip) or live without fft in python for now.

However the first proposed change is still necessary when no CUDA environment variables are defined. I am just not sure how deal with the lib/lib64 issue. Maybe ok to submit as is and see if someone runs into it.

**Comment by CoChrists** [comment]
Why has this been closed? Is there a fix?

**Comment by tjlane** [comment]
Must admit no real changes -- but I read over this and couldn't pinpoint what the exact issue was. If you have a specific error that is still current post it and I will consider reopening.
